pipeline:
  identifier: Build_jhttp_1733159980115
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: RichLiuHarnessLab
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: Rich
        repoName: jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
            paths: []
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: maven
                  identifier: buildpush
                  spec:
                    connectorRef: realfiction
                    image: harness-java-app
                    shell: Bash
                    command: |-
                      mvn clean install
                      mvn test
              - step:
                  type: Run
                  name: buildpushmaybe
                  identifier: buildpushmaybe
                  spec:
                    connectorRef: realfiction
                    image: harness-java-app
                    shell: Bash
                    command: |-
                      docker build -t realfiction/harness-java-app:latest .
                      docker push realfiction/harness-java-app:latest
          sharedPaths:
            - github
          buildIntelligence:
            enabled: false
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
        type: CI
        description: ""
