pipeline:
  identifier: Build_jhttp_1733159980115
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: RichLiuHarnessLab
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: Rich
        repoName: jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: buildpush
                  identifier: buildpush
                  spec:
                    connectorRef: account.harnessImage
                    image: harness-java-app-rxl
                    shell: Bash
                    command: |-
                      mvn clean install
                      mvn test
                      docker build -t realfiction/harness-kava-app-rxl:latest .
                      docker push ealfiction/harness-kava-app-rxl:latest
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: Minikube_Connector
              namespace: harness-java-app
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
        description: ""
