pipeline:
  identifier: Build_jhttp_1733218617887
  name: Build http try 2
  orgIdentifier: default
  projectIdentifier: RichLiuHarnessLab
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: Rich
        repoName: jhttp
  stages:
    - stage:
        name: build
        identifier: build
        template:
          templateRef: Deploy_Java
          versionLabel: "0.1"
