pipeline:
  identifier: Build_jhttp_1733159980115
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: RichLiuHarnessLab
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: Rich
        repoName: jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: GitClone
                  name: clone_jhttp
                  identifier: clone_jhttp
                  spec:
                    connectorRef: Rich
                    repoName: jhttp
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: maven
                  identifier: buildpush
                  spec:
                    connectorRef: realfiction
                    image: harness-java-app
                    shell: Bash
                    command: |-
                      mvn clean install
                      mvn test
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: realfiction
                    repo: harness-java-app
                    tags:
                      - latest
              - step:
                  type: Run
                  name: buildpushmaybe
                  identifier: buildpushmaybe
                  spec:
                    connectorRef: realfiction
                    image: harness-java-app
                    shell: Powershell
                    command: |-
                      docker build -t realfiction/harness-java-app:latest .
                      docker push realfiction/harness-java-app:latest
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: Minikube_Connector
              namespace: harness-java-app
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
        description: ""
