pipeline:
  identifier: Build_jhttp_1733218617887
  name: Build http try 2
  orgIdentifier: default
  projectIdentifier: RichLiuHarnessLab
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: Rich
        repoName: jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: maven build
                  spec:
                    shell: Bash
                    command: mvn clean package
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: realfiction
                    repo: harness-java-app
                    tags:
                      - latest
                    caching: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
