pipeline:
  name: Build http try 2
  identifier: Build_jhttp_1733218617887
  template:
    templateRef: BuildCI
    versionLabel: "0.1"
    templateInputs:
      properties:
        ci:
          codebase:
            build: <+input>
  projectIdentifier: RichLiuHarnessLab
  orgIdentifier: default
